<?php

namespace App\Console\Commands;

use App\Actions\Support\GenerateUniqueSlug;
use App\Models\ServiceCluster;
use Illuminate\Console\Attributes\Description;
use Illuminate\Console\Attributes\Signature;
use Illuminate\Console\Command;
use Illuminate\Support\Str;

#[Signature('app:fix-service-cluster-location-slugs {--dry-run : List the clusters that would change without saving anything} {--force : Skip the confirmation prompt}')]
#[Description('Regenerate service cluster slugs that were built from a title still containing {cidade}/{uf}/{regiao} tokens')]
class FixServiceClusterLocationSlugs extends Command
{
    public function handle(GenerateUniqueSlug $generateSlug): int
    {
        $clusters = ServiceCluster::query()
            ->where(function ($query) {
                $query->where('title', 'like', '%{cidade}%')
                    ->orWhere('title', 'like', '%{uf}%')
                    ->orWhere('title', 'like', '%{regiao}%');
            })
            ->get();

        if ($clusters->isEmpty()) {
            $this->info('No service cluster titles contain location tokens.');

            return self::SUCCESS;
        }

        $candidates = $clusters->filter(fn (ServiceCluster $cluster): bool => $this->looksAutoGenerated($cluster));

        $skipped = $clusters->count() - $candidates->count();

        if ($skipped > 0) {
            $this->warn("Skipping {$skipped} cluster(s) whose slug doesn't look like it was auto-generated from the title — looks manually edited already.");
        }

        if ($candidates->isEmpty()) {
            $this->info('Nothing to fix.');

            return self::SUCCESS;
        }

        $newSlugsById = $candidates->mapWithKeys(fn (ServiceCluster $cluster): array => [
            $cluster->id => $generateSlug(ServiceCluster::class, $this->stripLocationTokens($cluster->title), ignoreId: $cluster->id),
        ]);

        $this->table(
            ['ID', 'Title', 'Current slug', 'New slug'],
            $candidates->map(fn (ServiceCluster $cluster): array => [
                $cluster->id, $cluster->title, $cluster->slug, $newSlugsById[$cluster->id],
            ])->all(),
        );

        if ($this->option('dry-run')) {
            return self::SUCCESS;
        }

        if (! $this->option('force') && ! $this->confirm('Apply the new slugs above? Existing links to the current slugs will 404.')) {
            $this->info('Aborted.');

            return self::SUCCESS;
        }

        foreach ($candidates as $cluster) {
            $cluster->update(['slug' => $newSlugsById[$cluster->id]]);
        }

        $this->info("Updated {$candidates->count()} cluster slug(s).");

        return self::SUCCESS;
    }

    private function looksAutoGenerated(ServiceCluster $cluster): bool
    {
        $base = Str::slug($cluster->title);

        return (bool) preg_match('/^'.preg_quote($base, '/').'(-\d+)?$/', $cluster->slug);
    }

    private function stripLocationTokens(string $title): string
    {
        $stripped = str_replace(['{cidade}', '{uf}', '{regiao}'], '', $title);
        $stripped = preg_replace('/\s+(em|na|no|nas|nos|de|do|da|para)\s*$/iu', '', $stripped);
        $stripped = trim((string) $stripped);

        return $stripped !== '' ? $stripped : $title;
    }
}
